name: Coverage

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version: '1.21'
          check-latest: true

      - name: Download dependencies
        run: go mod download && go mod tidy

      - name: Run tests with coverage
        run: go test -v -coverpkg=./... -coverprofile=profile.out ./...

      - name: Extract cover profile
        run: go tool cover -func profile.out

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: profile.out
          if-no-files-found: error
          retention-days: 1

  upload:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage

      - name: Send coverage
        uses: codecov/codecov-action@v4
        with:
          file: profile.out